# ============================================================
# CELL BIB-3 -- MERGE references_v2 -> references_v3_merged.bib
# Applies BIB_ADJUDICATION_FINAL_v1 (+ DegFairGNN DOI 25558, READ-05).
# Rules: if an adjudicated entry's key OR any alias exists in v2, the
# entry BODY is replaced but the EXISTING key is preserved (so \cite
# commands stay valid). Otherwise the entry is appended under its
# canonical key. Any key containing 'loveland' is PURGED (M1) and
# subramonian2024degreebias is appended. v2 is never modified.
# CPU-only, ~10 seconds. Paste the full printed report back.
# ============================================================
from google.colab import drive
drive.mount('/content/drive', force_remount=False)
import glob, os, re, datetime

src = sorted(glob.glob('/content/drive/MyDrive/**/references_v2_autogenerated.bib', recursive=True))
assert src, '[FAIL] references_v2_autogenerated.bib not found'
SRC = src[0]
OUTDIR = os.path.dirname(SRC)
print('[src]', SRC)

raw = open(SRC, 'r', encoding='utf-8', errors='replace').read()

# ---------- parse v2 entries (brace-counting) ----------
def parse_bib(text):
    entries, i, n = [], 0, len(text)
    while True:
        m = re.search(r'@(\w+)\s*\{', text[i:])
        if not m: break
        start = i + m.start(); j = i + m.end(); depth = 1
        while j < n and depth > 0:
            if text[j] == '{': depth += 1
            elif text[j] == '}': depth -= 1
            j += 1
        block = text[start:j]
        km = re.match(r'@\w+\s*\{\s*([^,\s]+)\s*,', block)
        key = km.group(1) if km else None
        entries.append({'key': key, 'type': m.group(1).lower(), 'block': block})
        i = j
    return entries

v2 = parse_bib(raw)
v2keys = [e['key'] for e in v2]
print('[v2] entries:', len(v2))
dups = sorted({k for k in v2keys if v2keys.count(k) > 1})
if dups: print('[WARN] duplicate keys inside v2:', dups)

# ---------- adjudicated canonical entries ----------
ADJ = {
'kamalaruban2024fairfraud': r'''@inproceedings{kamalaruban2024fairfraud, author={Kamalaruban, Parameswaran and Pi, Yulu and Burrell, Stuart and Drage, Eleanor and Skalski, Piotr and Wong, Jason and Sutton, David}, title={Evaluating Fairness in Transaction Fraud Models: Fairness Metrics, Bias Audits, and Challenges}, booktitle={Proceedings of the 5th {ACM} International Conference on {AI} in Finance ({ICAIF} '24)}, publisher={ACM}, year={2024}, doi={10.1145/3677052.3698666}}''',
'jesus2022turning': r'''@inproceedings{jesus2022turning, author={Jesus, S{\'e}rgio and Pombal, Jos{\'e} and Alves, Duarte and Cruz, Andr{\'e} F. and Saleiro, Pedro and Ribeiro, Rita P. and Gama, Jo{\~a}o and Bizarro, Pedro}, title={Turning the Tables: Biased, Imbalanced, Dynamic Tabular Datasets for {ML} Evaluation}, booktitle={Advances in Neural Information Processing Systems 35 ({NeurIPS} 2022) Datasets and Benchmarks Track}, year={2022}}''',
'jensen2023fighting': r'''@article{jensen2023fighting, author={Jensen, Rasmus Ingemann Tuffveson and Iosifidis, Alexandros}, title={Fighting Money Laundering With Statistics and Machine Learning}, journal={{IEEE} Access}, volume={11}, pages={8889--8903}, year={2023}, doi={10.1109/ACCESS.2023.3239549}}''',
'mazumder2026explainable': r'''@article{mazumder2026explainable, author={Mazumder, Pristly Turjo}, title={Explainable and fair anti-money laundering models using a reproducible {SHAP} framework for financial institutions}, journal={Discover Artificial Intelligence}, volume={6}, number={1}, pages={262}, year={2026}, doi={10.1007/s44163-026-00944-7}}''',
'reite2023changes': r'''@article{reite2023changes, author={Reite, Endre J. and Oust, Are and Bang, Rebecca Margareta and Maurstad, Stine}, title={Changes in credit score, transaction volume, customer characteristics, and the probability of detecting suspicious transactions}, journal={Journal of Money Laundering Control}, volume={26}, number={6}, pages={1165--1178}, year={2023}, doi={10.1108/JMLC-06-2022-0087}}''',
'reite2025improving': r'''@article{reite2025improving, author={Reite, Endre Jo and Karlsen, Johan and Westgaard, Elias Grefstad}, title={Improving client risk classification with machine learning to increase anti-money laundering detection efficiency}, journal={Journal of Money Laundering Control}, volume={28}, number={1}, pages={93--107}, year={2025}, doi={10.1108/JMLC-03-2024-0040}, note={First published online 15 August 2024}}''',
'ravenda2015mafia': r'''@article{ravenda2015mafia, author={Ravenda, Diego and Argil{\'e}s-Bosch, Josep M. and Valencia-Silva, Maika M.}, title={Detection Model of Legally Registered Mafia Firms in {Italy}}, journal={European Management Review}, volume={12}, number={1}, pages={23--39}, year={2015}, doi={10.1111/emre.12039}}''',
'jofre2024financial': r'''@article{jofre2024financial, author={Jofre, Maria and Bosisio, Antonio and Riccardi, Michele}, title={Financial crime risk assessment: machine learning insights into ownership structures in secrecy firms}, journal={Global Crime}, volume={25}, number={3-4}, pages={242--267}, year={2024}, doi={10.1080/17440572.2024.2402848}}''',
'subramonian2024degreebias': r'''@inproceedings{subramonian2024degreebias, author={Subramonian, Arjun and Kang, Jian and Sun, Yizhou}, title={Theoretical and Empirical Insights into the Origins of Degree Bias in Graph Neural Networks}, booktitle={Advances in Neural Information Processing Systems 37 ({NeurIPS} 2024)}, year={2024}, url={https://proceedings.neurips.cc/paper_files/paper/2024/hash/0f94c552e5fe82bc152494985e34bd48-Abstract-Conference.html}}''',
'liu2023degfairgnn': r'''@inproceedings{liu2023degfairgnn, author={Liu, Zemin and Nguyen, Trung-Kien and Fang, Yuan}, title={On Generalized Degree Fairness in Graph Neural Networks}, booktitle={Proceedings of the {AAAI} Conference on Artificial Intelligence}, volume={37}, number={4}, pages={4525--4533}, year={2023}, doi={10.1609/aaai.v37i4.25558}}''',
'ye2025fairgse': r'''@misc{ye2025fairgse, author={Ye, Zhenqiang and Lu, Jinjie and Gu, Tianlong and Hao, Fengrui and Wang, Xuemin}, title={{FairGSE}: Fairness-Aware Graph Neural Network without High False Positive Rates}, year={2025}, eprint={2511.12132}, archivePrefix={arXiv}, primaryClass={cs.LG}, note={Accepted at {AAAI} 2026; proceedings record not yet located}}''',
'pleiss2017fairness': r'''@inproceedings{pleiss2017fairness, author={Pleiss, Geoff and Raghavan, Manish and Wu, Felix and Kleinberg, Jon and Weinberger, Kilian Q.}, title={On Fairness and Calibration}, booktitle={Advances in Neural Information Processing Systems 30 ({NIPS} 2017)}, pages={5680--5689}, year={2017}}''',
'tang2020degree': r'''@inproceedings{tang2020degree, author={Tang, Xianfeng and Yao, Huaxiu and Sun, Yiwei and Wang, Yiqi and Tang, Jiliang and Aggarwal, Charu and Mitra, Prasenjit and Wang, Suhang}, title={Investigating and Mitigating Degree-Related Biases in Graph Convolutional Networks}, booktitle={Proceedings of the 29th {ACM} International Conference on Information \& Knowledge Management ({CIKM} '20)}, pages={1435--1444}, publisher={ACM}, year={2020}, doi={10.1145/3340531.3411872}}''',
'johannessen2025finding': r'''@article{johannessen2025finding, author={Johannessen, Fredrik and Jullum, Martin}, title={Finding Money Launderers Using Heterogeneous Graph Neural Networks}, journal={The Journal of Finance and Data Science}, volume={11}, pages={100175}, year={2025}, doi={10.1016/j.jfds.2025.100175}}''',
'deprez2026network': r'''@article{deprez2026network, author={Deprez, Bruno and Vanderschueren, Toon and Baesens, Bart and Verdonck, Tim and Verbeke, Wouter}, title={Network Analytics for Anti-money Laundering---A Systematic Literature Review and Experimental Evaluation}, journal={{INFORMS} Journal on Data Science}, volume={5}, number={2}, pages={119--154}, year={2026}, doi={10.1287/ijds.2024.0042}}''',
'song2023fairfinancial': r'''@inproceedings{song2023fairfinancial, author={Song, Zixing and Zhang, Yuji and King, Irwin}, title={Towards Fair Financial Services for All: A Temporal {GNN} Approach for Individual Fairness on Transaction Networks}, booktitle={Proceedings of the 32nd {ACM} International Conference on Information and Knowledge Management ({CIKM} '23)}, pages={2331--2341}, publisher={ACM}, year={2023}, doi={10.1145/3583780.3615091}}''',
'bakry2024suppression': r'''@article{bakry2024suppression, author={Bakry, Ahmed N. and Alsharkawy, Almohammady S. and Farag, Mohamed S. and Raslan, K. R.}, title={Automatic Suppression of False Positive Alerts in Anti-Money Laundering Systems Using Machine Learning}, journal={The Journal of Supercomputing}, volume={80}, number={5}, pages={6264--6284}, year={2024}, doi={10.1007/s11227-023-05708-z}}''',
'wang2021confident': r'''@inproceedings{wang2021confident, author={Wang, Xiao and Liu, Hongrui and Shi, Chuan and Yang, Cheng}, title={Be Confident! {Towards} Trustworthy Graph Neural Networks via Confidence Calibration}, booktitle={Advances in Neural Information Processing Systems 34 ({NeurIPS} 2021)}, pages={23768--23779}, year={2021}}''',
'altman2023amlworld': r'''@inproceedings{altman2023amlworld, author={Altman, Erik and Blanu{\v{s}}a, Jovan and von Niederh{\"a}usern, Luc and Egressy, B{\'e}ni and Anghel, Andreea and Atasu, Kubilay}, title={Realistic Synthetic Financial Transactions for Anti-Money Laundering Models}, booktitle={Advances in Neural Information Processing Systems 36 ({NeurIPS} 2023) Datasets and Benchmarks Track}, pages={29851--29874}, year={2023}}''',
'hardt2016eqodds': r'''@inproceedings{hardt2016eqodds, author={Hardt, Moritz and Price, Eric and Srebro, Nati}, title={Equality of Opportunity in Supervised Learning}, booktitle={Advances in Neural Information Processing Systems 29 ({NIPS} 2016)}, pages={3323--3331}, year={2016}}''',
'oztas2023samld': r'''@inproceedings{oztas2023samld, author={Oztas, Berkan and Cetinkaya, Deniz and Adedoyin, Festus and Budka, Marcin and Dogan, Huseyin and Aksu, G{\"o}khan}, title={Enhancing Anti-Money Laundering: Development of a Synthetic Transaction Monitoring Dataset}, booktitle={2023 {IEEE} International Conference on e-Business Engineering ({ICEBE})}, address={Sydney, Australia}, pages={47--54}, year={2023}, doi={10.1109/ICEBE59045.2023.00028}}''',
'oztas2023perspectives': r'''@inproceedings{oztas2023perspectives, author={Oztas, Berkan and Cetinkaya, Deniz and Adedoyin, Festus and Budka, Marcin and Dogan, Huseyin and Aksu, G{\"o}khan}, title={Perspectives from Experts on Developing Transaction Monitoring Methods for Anti-Money Laundering}, booktitle={2023 {IEEE} International Conference on e-Business Engineering ({ICEBE})}, address={Sydney, Australia}, pages={39--46}, year={2023}, doi={10.1109/ICEBE59045.2023.00024}}''',
'cariello2024uif': r'''@techreport{cariello2024uif, author={Cariello, Pasquale and De Simoni, Marco and Iezzi, Stefano}, title={A Machine Learning Approach for the Detection of Firms Linked to Organised Crime in {Italy}, Based on Balance Sheet Data}, type={Quaderni dell'antiriciclaggio (Analisi e studi)}, number={22}, institution={Unit\`{a} di Informazione Finanziaria per l'{Italia} ({UIF}), Bank of {Italy}}, month=jun, year={2024}, url={https://uif.bancaditalia.it/pubblicazioni/quaderni/2024/quaderno-22-2024/index.html}}''',
'unicri2016organized': r'''@techreport{unicri2016organized, author={{United Nations Interregional Crime and Justice Research Institute ({UNICRI})}}, title={Organized Crime and the Legal Economy: The {Italian} Case}, institution={{UNICRI}}, address={Turin}, year={2016}, url={https://unicri.org/sites/default/files/2021-06/UNICRI_Organized_Crime_and_Legal_Economy_report.pdf}}''',
'redhead2021future': r'''@techreport{redhead2021future, author={Redhead, Matthew R.}, title={The Future of Transaction Monitoring: Better Ways to Detect and Disrupt Financial Crime}, type={{SWIFT} Institute Working Paper}, institution={{SWIFT} Institute}, month=may, year={2021}, url={https://www.swift.com/swift-resource/252235/download}, note={Cites {EY} conversion rates of 0.2, 1, 5, and 14 percent; industry working paper}}''',
'afme2021transaction': r'''@techreport{afme2021transaction, author={{Association for Financial Markets in Europe ({AFME})}}, title={Anti-Money Laundering Transaction Monitoring in the Markets Sector: An Industry Perspective}, institution={{AFME}}, month=oct, year={2021}, url={https://www.afme.eu/Portals/0/DispatchFeaturedImages/AFME_TransactionMonitoring2021-2.pdf}, note={Retail and business banking alert-to-{SAR} conversion typically 10--20 percent}}''',
'artingstall2016drivers': r'''@techreport{artingstall2016drivers, author={Artingstall, David and Dove, Nick and Howell, John and Levi, Michael}, title={Drivers \& Impacts of Derisking: A Study of Representative Views and Data in the {UK}}, institution={John Howell \& Co. Ltd. for the Financial Conduct Authority}, month=feb, year={2016}, url={https://www.fca.org.uk/publication/research/drivers-impacts-of-derisking.pdf}}''',
'fatf2021unintended': r'''@techreport{fatf2021unintended, author={{Financial Action Task Force}}, title={High-Level Synopsis of the Stocktake of the Unintended Consequences of the {FATF} Standards}, institution={{FATF}}, address={Paris}, month=oct, year={2021}, url={https://www.fatf-gafi.org/content/dam/fatf-gafi/reports/Unintended-Consequences.pdf}}''',
'fatf2025inclusion': r'''@techreport{fatf2025inclusion, author={{Financial Action Task Force}}, title={Guidance on Financial Inclusion and Anti-Money Laundering and Terrorist Financing Measures}, institution={{FATF}}, address={Paris}, month=jun, year={2025}, url={https://www.fatf-gafi.org/en/publications/Financialinclusionandnpoissues/guidance-financial-inclusion-aml-tf-measures.html}}''',
'gao2018derisking': r'''@techreport{gao2018derisking, author={{U.S. Government Accountability Office}}, title={{Bank Secrecy Act}: Derisking along the {Southwest} Border Highlights Need for Regulators to Enhance Retrospective Reviews}, number={GAO-18-263}, institution={U.S. Government Accountability Office}, address={Washington, DC}, month=feb, year={2018}, url={https://www.gao.gov/products/gao-18-263}}''',
'worldbank2015withdrawal': r'''@techreport{worldbank2015withdrawal, author={{World Bank Group}}, title={Withdrawal from Correspondent Banking: Where, Why, and What to Do About It}, institution={World Bank}, address={Washington, DC}, month=nov, year={2015}, url={http://hdl.handle.net/10986/23335}}''',
'erbenova2016imf': r'''@techreport{erbenova2016imf, author={Erbenov{\'a}, Michaela and Liu, Yan and Kyriakos-Saad, Nadim and L{\'o}pez-Mej{\'i}a, Alejandro and Gasha, Giancarlo and Mathias, Emmanuel and Norat, Mohamed and Fernando, Francisca and Almeida, Yasmin}, title={The Withdrawal of Correspondent Banking Relationships: A Case for Policy Action}, number={SDN/16/06}, institution={International Monetary Fund}, address={Washington, DC}, month=jun, year={2016}, doi={10.5089/9781498375092.006}}''',
'eba2022derisking': r'''@techreport{eba2022derisking, author={{European Banking Authority}}, title={Opinion of the {European Banking Authority} on `de-risking'}, number={EBA/Op/2022/01}, institution={European Banking Authority}, month=jan, year={2022}, url={https://www.eba.europa.eu/sites/default/files/document_library/Publications/Opinions/2022/Opinion%20on%20de-risking%20(EBA-Op-2022-01)/1025705/EBA%20Opinion%20and%20annexed%20report%20on%20de-risking.pdf}}''',
'treasury2023derisking': r'''@techreport{treasury2023derisking, author={{U.S. Department of the Treasury}}, title={The {Department of the Treasury}'s De-risking Strategy}, institution={U.S. Department of the Treasury}, address={Washington, DC}, month=apr, year={2023}, url={https://home.treasury.gov/system/files/136/Treasury_AMLA_23_508.pdf}, note={Mandated by the Anti-Money Laundering Act of 2020, Sec. 6215(c)(1)}}''',
'lexisnexis2023global': r'''@techreport{lexisnexis2023global, author={{LexisNexis Risk Solutions}}, title={True Cost of Financial Crime Compliance Report 2023}, institution={LexisNexis Risk Solutions}, year={2023}, url={https://risk.lexisnexis.com/about-us/press-room/press-release/20230926-global-financial-crime-compliance-costs}, note={Forrester Consulting study; global total {USD} 206.1 billion}}''',
'lexisnexis2024usca': r'''@techreport{lexisnexis2024usca, author={{LexisNexis Risk Solutions}}, title={True Cost of Financial Crime Compliance Study: {U.S.} and {Canada}}, institution={LexisNexis Risk Solutions}, year={2024}, url={https://risk.lexisnexis.com/about-us/press-room/press-release/20240221-true-cost-of-compliance-us-ca}, note={{USD} 61 billion total; 78 percent of small financial institutions report higher labor-related compliance cost increases}}''',
'agencies2021mrmbsa': r'''@techreport{agencies2021mrmbsa, author={{Board of Governors of the Federal Reserve System and Federal Deposit Insurance Corporation and Office of the Comptroller of the Currency}}, title={Interagency Statement on Model Risk Management for Bank Systems Supporting {Bank Secrecy Act}/Anti-Money Laundering Compliance}, month=apr, year={2021}, url={https://www.federalreserve.gov/supervisionreg/srletters/SR2108.htm}, note={Issued 9 April 2021 with {FinCEN} and {NCUA}; {SR} 21-8, {OCC} Bulletin 2021-19, {FDIC} {FIL}-27-2021; superseded 17 April 2026}}''',
'agencies2026mrm': r'''@techreport{agencies2026mrm, author={{Office of the Comptroller of the Currency and Board of Governors of the Federal Reserve System and Federal Deposit Insurance Corporation}}, title={Revised Guidance on Model Risk Management}, month=apr, year={2026}, url={https://www.federalreserve.gov/supervisionreg/srletters/SR2602.htm}, note={Issued 17 April 2026; {SR} 26-2, {OCC} Bulletin 2026-13; supersedes {SR} 11-7 and {SR} 21-8}}''',
'lin2024fraudgt': r'''@inproceedings{lin2024fraudgt, author={Lin, Junhong and Guo, Xiaojie and Zhu, Yada and Mitchell, Samuel and Altman, Erik and Shun, Julian}, title={{FraudGT}: A Simple, Effective, and Efficient Graph Transformer for Financial Fraud Detection}, booktitle={Proceedings of the 5th {ACM} International Conference on {AI} in Finance ({ICAIF} '24)}, publisher={ACM}, pages={292--300}, year={2024}, doi={10.1145/3677052.3698648}}''',
'chen2016xgboost': r'''@inproceedings{chen2016xgboost, author={Chen, Tianqi and Guestrin, Carlos}, title={{XGBoost}: A Scalable Tree Boosting System}, booktitle={Proceedings of the 22nd {ACM} {SIGKDD} International Conference on Knowledge Discovery and Data Mining ({KDD} '16)}, pages={785--794}, publisher={ACM}, year={2016}, doi={10.1145/2939672.2939785}}''',
'dwork2014dp': r'''@article{dwork2014dp, author={Dwork, Cynthia and Roth, Aaron}, title={The Algorithmic Foundations of Differential Privacy}, journal={Foundations and Trends in Theoretical Computer Science}, volume={9}, number={3-4}, pages={211--407}, year={2014}, doi={10.1561/0400000042}}''',
'fawkes2024fragility': r'''@inproceedings{fawkes2024fragility, author={Fawkes, Jake and Fishman, Nic and Andrews, Mel and Lipton, Zachary C.}, title={The Fragility of Fairness: Causal Sensitivity Analysis for Fair Machine Learning}, booktitle={Advances in Neural Information Processing Systems 37 ({NeurIPS} 2024) Datasets and Benchmarks Track}, year={2024}}''',
}

ALIASES = {
'kamalaruban2024fairfraud': ['kamalaruban2024fairness','kamalaruban2024'],
'altman2023amlworld': ['altman2023realistic','altman2024amlworld'],
'hardt2016eqodds': ['hardt2016equality'],
'oztas2023samld': ['oztas2023enhancing','oztas2023dataset','oztas2023synthetic'],
'gao2018derisking': ['gao2018bsa'],
'worldbank2015withdrawal': ['worldbank2015correspondent'],
'erbenova2016imf': ['erbenova2016withdrawal','imf2016withdrawal'],
'fatf2021unintended': ['fatf2021synopsis'],
'treasury2023derisking': ['ustreasury2023derisking'],
'reite2025improving': ['reite2024improving'],
'ravenda2015mafia': ['ravenda2015detection'],
'liu2023degfairgnn': ['liu2023degfair','liu2023degree'],
'subramonian2024degreebias': ['subramonian2024theoretical'],
'tang2020degree': ['tang2020investigating'],
'song2023fairfinancial': ['song2023tgnn','song2023towards'],
'johannessen2025finding': ['johannessen2023aml'],
'deprez2026network': ['deprez2025network'],
'mazumder2026explainable': ['mazumder2026shap'],
'cariello2024uif': ['cariello2024ml','cariello2024machine','uif2024quaderno22'],
'redhead2021future': ['redhead2021swift'],
'afme2021transaction': ['afme2021aml'],
'artingstall2016drivers': ['fca2016derisking'],
'fatf2025inclusion': ['fatf2025financialinclusion'],
'agencies2021mrmbsa': ['interagency2021aml'],
'agencies2026mrm': ['occ2026mrm'],
'chen2016xgboost': ['chen2016'],
'dwork2014dp': ['dwork2014algorithmic'],
}

def rekey(block, newkey):
    return re.sub(r'(@\w+\s*\{\s*)[^,\s]+(\s*,)', r'\g<1>'+newkey+r'\g<2>', block, count=1)

replaced, appended, purged = [], [], []
out_entries = []
consumed = set()

for e in v2:
    k = e['key'] or ''
    if 'loveland' in k.lower():
        purged.append(k); continue
    matched = None
    for canon, body in ADJ.items():
        if canon in consumed: continue
        if k == canon or k in ALIASES.get(canon, []):
            matched = canon; break
    if matched:
        out_entries.append(rekey(ADJ[matched], k))  # preserve existing key
        replaced.append((k, matched)); consumed.add(matched)
    else:
        out_entries.append(e['block'])

for canon, body in ADJ.items():
    if canon not in consumed:
        out_entries.append(body); appended.append(canon)

header = ('% references_v3_merged.bib generated ' + str(datetime.date.today()) +
          ' by CELL BIB-3 from references_v2_autogenerated.bib\n'
          '% per BIB_ADJUDICATION_FINAL_v1; existing cite keys preserved on replacement.\n\n')
merged = header + '\n\n'.join(out_entries) + '\n'
OUT = os.path.join(OUTDIR, 'references_v3_merged.bib')
open(OUT, 'w', encoding='utf-8').write(merged)

# ---------- report ----------
print('\n[REPLACED]', len(replaced))
for k, c in replaced: print('   kept key', k, '<- adjudicated', c)
print('[APPENDED]', len(appended))
for c in appended: print('   +', c)
print('[PURGED]', purged if purged else 'none')
v3 = parse_bib(merged)
print('[v3] entries:', len(v3))
keys3 = sorted([x['key'] for x in v3])
print('[v3 keys]'); print(', '.join(keys3))
dois = {}
for x in v3:
    dm = re.search(r'doi\s*=\s*\{([^}]+)\}', x['block'], re.I)
    if dm: dois.setdefault(dm.group(1).strip().lower(), []).append(x['key'])
dupdoi = {d: ks for d, ks in dois.items() if len(ks) > 1}
print('[DOI duplicates across keys]', dupdoi if dupdoi else 'none')
em = merged.count('\u2014')
print('[em-dash U+2014 chars in v3]', em, '(titles should use TeX --- instead)' if em else '')
print('[saved]', OUT)
print('[DONE BIB-3]')
